### ISSUE TITLE
Monitor Produces Duplicates 

### ISSUE THREAD

**Issue by addapptation-choey** [stakater/IngressMonitorController#123] opened 2018-10-09 16:37 UTC
I'm trying out IngressMonitorController with StatusCake for my K8s cluster.

It appears that oftentimes an ingress entity is created, it is processed twice by the monitor, resulting in  two identical tests being added to StatusCake.

I'm using Kubernetes Server v1.11.3

There does appear to be an error in the log when this occurs:

```2018/10/09 16:11:55 Monitor URL: https://test-jnf-app1.testdomain.com/app_status
2018/10/09 16:11:55 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:11:56 Monitor Added: 3534589
2018/10/09 16:11:56 Monitor Name: jnf-app1
2018/10/09 16:11:56 Monitor URL: https://test-jnf-app1.testdomain.com/app_status
2018/10/09 16:11:56 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:11:57 Monitor Added: 3534590
2018/10/09 16:11:57 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:11:57 Cannot find monitor with name: jnf-app2
2018/10/09 16:11:57 Monitor Name: jnf-app2
2018/10/09 16:11:57 Monitor URL: https://test-jnf-app2.testdomain.com/app_status
2018/10/09 16:11:57 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:11:58 Monitor Added: 3534591
2018/10/09 16:11:58 Monitor Name: jnf-app2
2018/10/09 16:11:58 Monitor URL: https://test-jnf-app2.testdomain.com/app_status
2018/10/09 16:11:59 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:11:59 Monitor Added: 3534592
2018/10/09 16:13:00 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:13:00 Cannot find monitor with name: testdomain-projects
2018/10/09 16:13:24 Monitor Name: projects
2018/10/09 16:13:24 Monitor URL: https://test-projects.testdomain.com/app_status
2018/10/09 16:13:25 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:13:26 Monitor Added: 3534595
2018/10/09 16:13:28 Monitor Name: projects
2018/10/09 16:13:28 Monitor URL: https://test-projects.testdomain.com/app_status
2018/10/09 16:13:28 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:13:29 Monitor Added: 3534596
2018/10/09 16:15:11 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:15:11 Cannot find monitor with name: jnf-app2
2018/10/09 16:15:44 Monitor Name: jnf-app2
2018/10/09 16:15:44 Monitor URL: https://test-jnf-app2.testdomain.com/app_status
2018/10/09 16:15:45 json: cannot unmarshal number 42.86 into Go struct field StatusCakeMonitorMonitor.Uptime of type int
2018/10/09 16:15:45 Monitor Added: 3534601
2018/10/09 16:15:57 Monitor Name: jnf-app2
2018/10/09 16:15:57 Monitor URL: https://test-jnf-app2.testdomain.com/app_status
2018/10/09 16:15:58 Monitor already exists for ingress: jnf-app2
2018/10/09 16:15:59 Monitor couldn't be updated: jnf-app2
2018/10/09 16:15:59 No data has been updated (is any data different?)
```

**Comment by rasheedamir** [comment] 2018-10-09 19:50
@Anish-Gupta-Bose since you added StatusCake support I wonder if you can take a look?

@waseem-h what is your thought on this issue?

**Comment by waseem-h** [comment] 2018-10-12 03:36
One thing I can see from the logs is that unmarshaling statuscake responses is failing due to invalid data type. I've fixed the issue but was unable to reproduce the issue where IMC is creating duplicates. Can you please provide steps and config to reproduce this? @addapptation-choey

**Comment by rasheedamir** [comment] 2018-10-17 19:47
@addapptation-choey is this still an issue or we can close it?

**Comment by rasheedamir** [comment] 2018-10-18 15:44
Ok cool good to know! We will close this for now and if someone reports it again then we can open it.

**Closed by rasheedamir** 2018-10-18 15:44 UTC
