### ISSUE TITLE
Cross namespace support?

### ISSUE THREAD

**Issue by drubin** [stakater/IngressMonitorController#48] opened 2018-04-26 11:45 UTC
Is it possible to run this in a different namespace to the ingess rules it reads? 

I see you have to pass the namespace in as an ENV variable https://github.com/stakater/IngressMonitorController/blob/master/src/main.go#L12. But that isn't how most of our ingress controllers are configured. 

So it would be nice if this could be deployed in a similar fashion to that, vs every namespace needing a custom ingress monitor controller?

**Comment by waseem-h** [comment] 2018-04-26 11:59
One way of doing this would be to provide the namespaces to watch in the configmap and update the RBAC so that the controller can watch ingresses in those namespaces as well. Unfortunately this is not supported yet but we would be happy if you could implement this change and create a PR

**Comment by waseem-h** [comment] 2018-04-27 06:35
The problem is that the service account was created in a different namespace. You need to change the namespace of the service account here: https://github.com/stakater/IngressMonitorController/blob/master/kubernetes/manifests/rbac.yaml#L54

After changing you can run 
```
kubectl apply -f rbac.yaml --namespace uptime-robot
```

**Comment by drubin** [comment] 2018-04-27 07:45
@waseem-h Yes sorry you were right sorry about that.. I copied the wrong error from the logs. This is what I originally got before changing the namespace as you mentioned.

After I did that I got the following errors, which I thought were confusing considering I was using the exact rules in the manifests file. Could there be a difference between k8s versions I am running? Or do I need to explicitly whitelist v1beta1.ingress as well?

```E0427 07:42:16.169454       1 reflector.go:199] controller.go:79: Failed to list *v1beta1.Ingress: Unauthorized
E0427 07:42:17.174078       1 reflector.go:199] controller.go:79: Failed to list *v1beta1.Ingress: Unauthorized```

Btw I managed to get this working with changing the rolebinding to cluster-admin, but this is less than ideal and I would prefer to try fix the rbac configurations.

**Comment by rasheedamir** [comment] 2018-04-27 13:42
@drubin which version of k8s are you running?

**Comment by drubin** [comment] 2018-04-27 15:27
@rasheedamir 1.9.4 on gke.

**Comment by waseem-h** [comment] 2018-04-27 19:42
Can you share your deployed resource's yaml? Run kubectl get -o yaml and post yaml here so I can see what's wrong. Maybe you haven't assigned the same service account to the deployment

**Comment by drubin** [comment] 2018-05-04 07:01
@rasheedamir @waseem-h Sorry about the late reply. I will post the yaml today. I just have to re-install it in a cluster as I removed it when the rbac wasn't working.

**Comment by rasheedamir** [comment] 2018-05-04 07:15
@drubin cool no problem!

**Comment by rasheedamir** [comment] 2018-05-08 07:29
@drubin today we found out a drawback of running IMC per namespace; that is if someone deletes a namespace then there will be lingering monitors; which someone will have to delete manually

so, the solution is to run IMC in default namespace and let it watch over all namespaces

wondering if you would like to implement this change? @waseem-h can give high level pointers.

**Comment by rasheedamir** [comment] 2018-06-19 15:52
@drubin now this feature is in place; please test and let us know. I am going to close it now; but if you find its not working as expected then please let us know.

**Closed by rasheedamir** 2018-06-19 15:52 UTC
Labels: kind/question, workflow/done
